apiVersion: apps/v1
kind: Deployment

metadata:
  name: k8s-learn-api
  namespace: s11gabriel

spec:
  replicas: 1

  selector:
    matchLabels:
      app: k8s-learn-api

  template:
    metadata:
      labels:
        app: k8s-learn-api

    spec:
      containers:
        - name: backend
          image: ghcr.io/gab569/k8s-learn-api:0b4ed2b88900ce962e42aa4edbd963ccb605a46b
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 4000
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL