apiVersion: v1
kind: Service

metadata:
  name: k8s-learn-api-service
  namespace: s11gabriel

spec:
  type: ClusterIP

  selector:
    app: k8s-learn-api

  ports:
    - port: 4000
      targetPort: 4000
      protocol: TCP